#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.1k.1 ./index -t ~/Data/delta1/1k_matching_1.txt -z 256 -o output
valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.1k.2 ./index -t ~/Data/delta1/1k_matching_2.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.1k.3 ./index -t ~/Data/delta1/1k_matching_3.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.1k.4 ./index -t ~/Data/delta1/1k_matching_4.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.1k.5 ./index -t ~/Data/delta1/1k_matching_5.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.1k.6 ./index -t ~/Data/delta1/1k_matching_6.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.1k.7 ./index -t ~/Data/delta1/1k_matching_7.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.1k.8 ./index -t ~/Data/delta1/1k_matching_8.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.1k.9 ./index -t ~/Data/delta1/1k_matching_9.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.1k.10 ./index -t ~/Data/delta1/1k_matching_10.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.2k.1 ./index -t ~/Data/delta1/2k_matching_1.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.2k.2 ./index -t ~/Data/delta1/2k_matching_2.txt -z 256 -o output
valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.2k.3 ./index -t ~/Data/delta1/2k_matching_3.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.2k.4 ./index -t ~/Data/delta1/2k_matching_4.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.2k.5 ./index -t ~/Data/delta1/2k_matching_5.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.2k.6 ./index -t ~/Data/delta1/2k_matching_6.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.2k.7 ./index -t ~/Data/delta1/2k_matching_7.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.2k.8 ./index -t ~/Data/delta1/2k_matching_8.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.2k.9 ./index -t ~/Data/delta1/2k_matching_9.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.2k.10 ./index -t ~/Data/delta1/2k_matching_10.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.4k.1 ./index -t ~/Data/delta1/4k_matching_1.txt -z 256 -o output
valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.4k.2 ./index -t ~/Data/delta1/4k_matching_2.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.4k.3 ./index -t ~/Data/delta1/4k_matching_3.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.4k.4 ./index -t ~/Data/delta1/4k_matching_4.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.4k.5 ./index -t ~/Data/delta1/4k_matching_5.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.4k.6 ./index -t ~/Data/delta1/4k_matching_6.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.4k.7 ./index -t ~/Data/delta1/4k_matching_7.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.4k.8 ./index -t ~/Data/delta1/4k_matching_8.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.4k.9 ./index -t ~/Data/delta1/4k_matching_9.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.4k.10 ./index -t ~/Data/delta1/4k_matching_10.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.8k.1 ./index -t ~/Data/delta1/8k_matching_1.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.8k.2 ./index -t ~/Data/delta1/8k_matching_2.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.8k.3 ./index -t ~/Data/delta1/8k_matching_3.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.8k.4 ./index -t ~/Data/delta1/8k_matching_4.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.8k.5 ./index -t ~/Data/delta1/8k_matching_5.txt -z 256 -o output
valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.8k.6 ./index -t ~/Data/delta1/8k_matching_6.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.8k.7 ./index -t ~/Data/delta1/8k_matching_7.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.8k.8 ./index -t ~/Data/delta1/8k_matching_8.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.8k.9 ./index -t ~/Data/delta1/8k_matching_9.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.8k.10 ./index -t ~/Data/delta1/8k_matching_10.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.16k.1 ./index -t ~/Data/delta1/16k_matching_1.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.16k.2 ./index -t ~/Data/delta1/16k_matching_2.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.16k.3 ./index -t ~/Data/delta1/16k_matching_3.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.16k.4 ./index -t ~/Data/delta1/16k_matching_4.txt -z 256 -o output
valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.16k.5 ./index -t ~/Data/delta1/16k_matching_5.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.16k.6 ./index -t ~/Data/delta1/16k_matching_6.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.16k.7 ./index -t ~/Data/delta1/16k_matching_7.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.16k.8 ./index -t ~/Data/delta1/16k_matching_8.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.16k.9 ./index -t ~/Data/delta1/16k_matching_9.txt -z 256 -o output
#valgrind --tool=massif --time-unit=ms --massif-out-file=massif.out.16k.10 ./index -t ~/Data/delta1/16k_matching_10.txt -z 256 -o output